### ISSUE TITLE
Read Parquet data as a  Stream?

### ISSUE THREAD

**Issue by javafanboy** [jerolba/parquet-carpet#46]
I have very successfully created Parquet data and streamed it to an AWS S3 object with Carpet (performance turned out to be quite good) but now I would like to read an S3 Parquet object in the same way. I do not see a constructor for CarpetReader that accepts a stream - is this something you are considering to support? Not sure if this is even supported by the Apache Parquet libraries?!

Reading Parquet in streaming mode (row group by row group and iterate record by record within them) would be useful to consume larger datasets than what fits on local disk and also allow quicker reading if data does not need to be stored on disk first.

In my case I would have liked to read an huge S3 object in Parquet format as a stream, filter the received data (exclude some outdated records), add some new records in the right place and directly upload to a new version to S3 using a steam (already supported by Carpet).

This is of course a somewhat limited use-case as one cant sort the whole dataset (as I am not holding it in memory or even on disk) only merge in new records into the existing sorting order but in some cases it is all that is needed.

**Comment by jerolba** [comment]
Hi @javafanboy 

No, you can not read a Parquet file in streaming. To support writing in streaming, Parquet persist all metainformation generated writing the information at the end of the file. Then, to start reading the file it needs to go to the end of the file and read the footer. With that information seeks around the file reading requested information.

In this article you can learn about its structure and explanation of the footer: 
https://www.linkedin.com/pulse/all-you-need-know-parquet-file-structure-depth-rohan-karanjawala/

To implement a stream reader Parquet ask you to extend the class [SeekableInputStream](https://github.com/apache/parquet-java/blob/08a4e7e6279f8c3b8558bd294fee4489a96d0db1/parquet-common/src/main/java/org/apache/parquet/io/SeekableInputStream.java#L49) that has a `seek` method.

With a streaming strategy you can not implement features like schema projection or predicate pushdown.

**Comment by javafanboy** [comment]
Thanks for the quick reply I had forgotten that Parquet uses a footer and
not a header for the metadata :-)
